---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: ff5ab13fb1ae15c6f3ac33633e9abb8bceb9be26
    fabric8.io/git-branch: micro-config
    fabric8.io/git-url: https://github.com/yangd2019/DO288-apps
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    app: hello
    provider: fabric8
    version: "1.0"
    group: com.redhat.training.openshift
  name: hello
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello
    provider: fabric8
    group: com.redhat.training.openshift
